### ISSUE TITLE
Pauvre personne

### ISSUE THREAD

**Issue by Bleu-No** [venaxyt/Ares#13]
ça doit faire mal petit, après toi aussi tu veux jouer dans la cours des grands alors que tu n'es rien. Dommage pour toi...

https://github.com/Bleu-No/Fuck-Ares

**Comment by NotPunchnox** [comment]
C'est pas ce que j'appelle jouer dans la cours des grands par contre ton issue est pas marrante pour le coup :flushed:

**Comment by Bleu-No** [comment]
Ok 🤷‍♂️
